spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true